# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ Milestone-2 ]
  pull_request:
    branches: [ Milestone-2 ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  gitHubActionForPytest:
    name: Github Action for pytest
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@Milestone-2
      - name: Github Action for pytest
        uses: cclauss/Github-action-for-pytest@Milesonte-2
        with:
          args: python setup.py develop && pytest
